apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server-ctn
        image: springcommunity/spring-petclinic-admin-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 3
      initContainers:
        - name: init-config-server-ctn
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until wget http://config-server:8888/actuator; do echo waiting for config-server; sleep 2; done;']
        - name: init-discovery-server-ctn
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until wget http://discovery-server:8761/actuator/health; do echo waiting for discovery-server; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 32090
    protocol: TCP
    targetPort: 9090
  selector:
    app: admin-server