apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-ctn
        image: springcommunity/spring-petclinic-api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      initContainers:
        - name: init-config-server-ctn
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until wget http://config-server:8888/actuator; do echo waiting for config-server; sleep 2; done;']
        - name: init-discovery-server-ctn
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until wget http://discovery-server:8761/actuator/health; do echo waiting for discovery-server; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway