apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server-ctn
        image: springcommunity/spring-petclinic-config-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            # /{application}/{profile}[/{label}] is HTTP service resources of Spring Cloud Config
            path: /actuator
            port: 8888
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 31888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server