apiVersion: v1
kind: Service
metadata:
  name: grafana-server
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32091
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus-server
    app.kubernetes.io/name: grafana