apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - name: tracing-server-ctn
        image: openzipkin/zipkin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9411
        readinessProbe:
          httpGet:
            path: /zipkin/
            port: 9411
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
spec:
  type: NodePort
  ports:
  - port: 9411
    nodePort: 32411
    protocol: TCP
    targetPort: 9411
  selector:
    app: tracing-server